### ISSUE TITLE
Client GUI is not closing after kicking out

### ISSUE THREAD

**Issue by naoh-hcl** [0smic/DownStream#1] opened 2024-05-11 18:06 UTC
When I kick out a user.  GUI of that user is not responding and not closing.

**To Recreate it**

-  use kick command to kick out a user
-  That user gets a notification of the kick out
-  Click ok

Then the GUI of that user is not responding.
Also, the 'ban' command is not working. It's showing Invalid command after entering

**Comment by 0smic** [comment] 2024-05-17 19:19
**GUI Not Responding issue**

It was caused by a thread working on the background, we finally able to fix it
Remember there is auto closing the application after the client got kicked out (you want to do it manually)

**Ban Invalid issue**

The Func was incomplete, that's the reason it showing invalid,
 We will update u when it is fixed

**Comment by 0smic** [comment] 2024-05-17 19:20
**GUI Not Responding issue**

It was caused by a thread working on the background, we finally able to fix it
Remember there is auto closing the application after the client got kicked out (you want to do it manually)

**Ban Invalid issue**

The func was incomplete, that's the reason it showing invalid,
 We will update u when it is fixed

**Closed as completed by 0smic** 2024-05-17 19:20 UTC
